data_path: meshgraph_dataset.h5
input_dim_nodes: 5
input_dim_edges: 4
output_dim: 1
aggregation: sum
hidden_dim_node_encoder: 128
hidden_dim_edge_encoder: 128
hidden_dim_node_decoder: 128
normalization: min-max

loss: LogCoshLoss
main_loss: MultiComponentLoss
batch_size: 2
lr: 0.001
epochs: 100
amp: true
wandb_mode: disabled
ckpt_path: checkpoints/shell_model.pt
num_training_samples: 1
num_validation_samples: 1
num_test_samples: 1
