hydra:
    run:
        dir: ./shell_mgn/500_epoch_outputs
    job:
        chdir: True

ckpt_path: ./shell_mgn/500_epoch_checkpoints
ckpt_name: ./shell.pt
data_path: /home/sces201/Afeera/MeshGraphNet/scripts/meshgraph_dataset_dgl.h5  # -> path to data file - hdf5
results_dir: ./shell_mgn/500_epoch_results

input_dim_nodes: 6 # 2d pos , 2d spc 2d force
input_dim_edges: 3 # 2d disp, 1d norm
output_dim: 1 # disp_x,y,z | 1d cause multi heads

hidden_dim_node_encoder: 256
hidden_dim_edge_encoder: 256
hidden_dim_node_decoder: 256


invar_keys: ["pos", "spc", "load"]
normalize_keys: ["disp_y", "disp_z", "load"]

aggregation: "sum"
batch_size: 50
epochs: 500

num_training_samples: 1200
num_validation_samples: 150
num_test_samples: 150

lr: 1e-3

amp: False
jit: False
wandb_mode: "online"

loss:
    MSELoss

normalization:
    z_score